version: '3.8'

services:
  app:
    container_name: backend
    build:
      context: ./backend
      dockerfile: ./Walory Backend/Dockerfile
    image: walory.azurecr.io/walory-api:latest
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Default=${CONNECTION_STRING}
    depends_on:
      - db
      
  frontend:
    container_name: frontend
    build:
      context: ./frontend/walory-portal
      dockerfile: Dockerfile
    image: walory.azurecr.io/walory-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - app
      
  db:
    container_name: postgreSQL
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
      
volumes:
  pgdata: