# version: '3.8'
# Znajdujesz się w katalogu "Walory Backend"
# a projekty Application i Infrastracture są w katalogu nadrzędnym
services:
  app:
    container_name: walory-backend
    build:
      context: ..
      dockerfile: ./Walory Backend/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Default=Host=db;Port=5432;Database=walorydb;Username=user;Password=Zaq12wsx #Lol podobno to zalatwie sprawe konfiguracji appsetting.json
    depends_on:
      - db

  db:
    container_name: walory-postgreSQL
    image: postgres:15
    environment:
      POSTGRES_DB: walorydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: Zaq12wsx
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  pgdata:
